indent_type = "Tabs"
indent_width = 4
quote_style = "ForceDouble"
line_endings = "Unix"
column_width = 120
call_parentheses = "Always"
collapse_simple_statement = "FunctionOnly"


[sort_requires]
enabled = true
